name: 'Action Test'
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'
    paths:
      - "**.ts"
      - ".github/workflows/action_check.yml"
      - "action.yml"
      - "dist/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test Purge all
        uses: ./
        with:
          api_token: ${{ secrets.TEST_TOKEN }}
          zone: ${{ secrets.TEST_ZONE }}

      - name: Test URL List
        uses: ./
        with:
          api_token: ${{ secrets.TEST_TOKEN }}
          zone: ${{ secrets.TEST_ZONE }}
          URLs: |
            https://community.cyberjake.xyz/example1
            https://community.cyberjake.xyz/example2

