name: 'Typescript Test'
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - "**.ts"
      - ".github/workflows/typescript.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.1.4

      - name: Lint
        run: pnpm lint

      - name: Check format
        run: pnpm format-check

      - name: Run tests
        run: pnpm test