name: 'Typescript Test'
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - "**.ts"
      - ".github/workflows/typescript.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install Packages
        run: yarn install

      - name: Lint
        run: yarn run lint

      - name: Check format
        run: yarn run format-check

      - name: Run tests
        run: yarn run test